### ISSUE TITLE
Silent mode?

### ISSUE THREAD

**Issue by aliakhtar** [michaelmosmann/embedmongo.flapdoodle.de#12]
Great project, but it produces a lot of output which makes it difficult to find the output that matters. Is it possible to start mongo in silent mode where it doesn't log the output to console?

**Comment by aliakhtar** [comment]
`.withLaunchArgument("--quiet")` was accepted but it didn't seem to do anything. Also tried adding a noop process listener, but no effect.

**Comment by michaelmosmann** [comment]
please create an issue at https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo if needed.. will close this.
